import { describe, expect, it } from 'vitest';

import { extractHeadings, injectHeadingIds } from '../headings';

/**
 * The invariant that matters: an id generated by `injectHeadingIds` must equal
 * the one `extractHeadings` puts in the contents list. If they diverge, the
 * links render and silently scroll nowhere — no error, no failed request.
 */
const BODY = `
<p>Intro paragraph.</p>
<h2>Introduction</h2>
<p>Body.</p>
<h2>AI in Diagnostic Imaging</h2>
<h3>Sub point</h3>
<p>More.</p>
<h4>Too deep for the contents list</h4>
`;

describe('extractHeadings', () => {
  it('returns h2 and h3 in document order with slugged ids', () => {
    expect(extractHeadings(BODY)).toEqual([
      { id: 'introduction', text: 'Introduction', level: 2 },
      { id: 'ai-in-diagnostic-imaging', text: 'AI in Diagnostic Imaging', level: 2 },
      { id: 'sub-point', text: 'Sub point', level: 3 },
    ]);
  });

  it('ignores h4 and below, which would make the list noise', () => {
    expect(extractHeadings(BODY).map((h) => h.text)).not.toContain(
      'Too deep for the contents list',
    );
  });

  it('takes the label from text content, not inner markup', () => {
    const out = extractHeadings('<h2>The <em>real</em> cost of <code>await</code></h2>');
    expect(out[0]?.text).toBe('The real cost of await');
    expect(out[0]?.id).toBe('the-real-cost-of-await');
  });

  it('keeps headings that carry attributes', () => {
    const out = extractHeadings('<h2 class="wp-block-heading">Styled</h2>');
    expect(out).toHaveLength(1);
    expect(out[0]?.id).toBe('styled');
  });

  it('disambiguates repeated headings instead of colliding', () => {
    const out = extractHeadings('<h2>Notes</h2><h2>Notes</h2><h2>Notes</h2>');
    expect(out.map((h) => h.id)).toEqual(['notes', 'notes-2', 'notes-3']);
  });

  it('skips an empty heading rather than emitting a blank entry', () => {
    expect(extractHeadings('<h2></h2><h2>  </h2><h2>Real</h2>')).toEqual([
      { id: 'real', text: 'Real', level: 2 },
    ]);
  });

  it('falls back to a usable id when the text slugs to nothing', () => {
    // A heading of only punctuation or emoji still needs an anchor.
    const out = extractHeadings('<h2>—</h2>');
    expect(out).toHaveLength(1);
    expect(out[0]?.id).toBeTruthy();
  });

  it('returns nothing for empty or heading-free content', () => {
    expect(extractHeadings('')).toEqual([]);
    expect(extractHeadings('<p>No headings here.</p>')).toEqual([]);
  });
});

describe('injectHeadingIds', () => {
  it('adds ids matching the extracted list', () => {
    const withIds = injectHeadingIds(BODY);
    for (const heading of extractHeadings(BODY)) {
      expect(withIds, heading.id).toContain(`id="${heading.id}"`);
    }
  });

  it('preserves existing attributes on the heading', () => {
    const out = injectHeadingIds('<h2 class="wp-block-heading">Styled</h2>');
    expect(out).toContain('class="wp-block-heading"');
    expect(out).toContain('id="styled"');
  });

  it('leaves the heading text and level untouched', () => {
    const out = injectHeadingIds('<h3>The <em>real</em> cost</h3>');
    expect(out).toContain('<h3');
    expect(out).toContain('The <em>real</em> cost');
    expect(out).toContain('</h3>');
  });

  it('is idempotent — re-running does not double up ids', () => {
    const once = injectHeadingIds(BODY);
    const twice = injectHeadingIds(once);
    expect(twice).toBe(once);
  });

  it('respects an id already present and does not collide with it', () => {
    const out = injectHeadingIds('<h2 id="notes">First</h2><h2>Notes</h2>');
    // The first keeps its own id; the second must not also claim "notes".
    expect(out).toContain('<h2 id="notes">First</h2>');
    expect(out).toContain('id="notes-2"');
  });

  it('disambiguates repeats the same way extraction does', () => {
    const html = '<h2>Notes</h2><h2>Notes</h2>';
    const out = injectHeadingIds(html);
    expect(out).toContain('id="notes"');
    expect(out).toContain('id="notes-2"');
    expect(extractHeadings(html).map((h) => h.id)).toEqual(['notes', 'notes-2']);
  });

  it('does not touch content without headings', () => {
    const html = '<p>Nothing to do.</p>';
    expect(injectHeadingIds(html)).toBe(html);
  });
});
