-- 0010_lead_magnets.sql — conditional lead capture on post pages
--
-- The WordPress equivalent of this is a popup plugin: build a form, attach it to
-- some posts and not others, collect emails. Three tables reproduce that here.
--
--   lead_magnets         the offer and its copy — one row per thing you give away
--   lead_magnet_targets  which posts it appears on
--   leads                what came back
--
-- WHY TARGETS ARE A SEPARATE TABLE. The obvious shortcut is a `category_ids
-- uuid[]` column on lead_magnets. That cannot express "this post but not that
-- one", it has no referential integrity — a deleted category leaves a dangling
-- uuid in an array no foreign key is watching — and it makes the resolver a
-- containment scan instead of an indexed lookup. A row per rule costs one join
-- and gets all three back.
--
-- WHY THE COPY IS PLAIN TEXT, NOT HTML. Every other authored field on this
-- platform runs through the sanitiser on write, and widening that allowlist has
-- a documented cost (see the note on posts.content_html in the README). A lead
-- magnet card is a heading, a sentence and a button; none of it needs markup,
-- and text rendered as text needs no allowlist at all. If rich copy is ever
-- wanted here, it goes through sanitizePageHtml — it does NOT get a new
-- untrusted HTML path.

-- ---------------------------------------------------------------------------
-- lead_magnets
-- ---------------------------------------------------------------------------

create table public.lead_magnets (
  id            uuid primary key default gen_random_uuid(),
  site_id       uuid not null references public.sites(id) on delete cascade,

  /*
   * Stable public identifier. This is what the capture endpoint accepts and
   * what gets forwarded to the webhook, so downstream automations key off a
   * name rather than a uuid — an n8n branch reading `equipment-financing-toolkit`
   * survives the row being rebuilt, which one reading a uuid does not.
   */
  slug          text not null,

  -- Internal label for the admin list. Never rendered to a reader.
  name          text not null,

  -- The card, as the reader sees it.
  heading       text not null,
  body          text,
  button_label  text not null default 'Send it to me',
  success_message text not null default 'Check your inbox — it is on the way.',

  /*
   * Whether the card asks for a first name as well as an address.
   *
   * A real setting rather than a fixed choice, because it is a real trade: an
   * extra field costs conversions, and a name is what makes the follow-up
   * email readable. Which way that goes depends on the offer, which is exactly
   * the kind of decision the admin exists for. Default off — email-only
   * converts better, so the cost should be opted into.
   */
  collect_name  boolean not null default false,

  /*
   * Optional small print under the button. Nullable rather than defaulted:
   * consent wording is a legal decision per offer, and inventing a default
   * would put words in the site owner's mouth on every new magnet.
   */
  consent_text  text,

  /*
   * Where the asset actually lives. A plain URL, not a media(id) reference.
   *
   * The media table and its bucket exist for images the renderer reasons about
   * — width, height, blur placeholder, next/image — and a PDF has none of that.
   * A URL also covers the common case where the file is already hosted
   * somewhere else (Drive, S3, the CRM) and re-uploading it would just create a
   * second copy to keep in sync.
   *
   * Nullable, because delivery can be email-only: with no URL the card shows
   * the success message and nothing else, and the webhook consumer sends the
   * file. With one, the reader also gets an immediate link — which is worth
   * having, since it is the only delivery path that cannot be lost to a spam
   * filter.
   *
   * NOT sent to the browser with the rest of the card. The capture endpoint
   * returns it in the success response instead, so the URL is not sitting in
   * the page source of every article the offer appears on. That is not real
   * access control — anyone willing to type an address gets it, which is the
   * deal — but a gate whose answer is in view-source is not a gate at all.
   * The anon key never reaches a browser here (see env.ts), so reading this
   * column server-side keeps it server-side.
   */
  asset_url     text,

  -- Off rather than deleted, so a seasonal offer keeps its leads and its copy.
  active        boolean not null default true,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint lead_magnets_slug_per_site_unique unique (site_id, slug),
  -- Same shape as sites_slug_format: this one is generated by the admin from
  -- the name rather than transcribed from an existing URL, so unlike a post
  -- slug it can afford to be strict.
  constraint lead_magnets_slug_format check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint lead_magnets_name_present check (name <> ''),
  constraint lead_magnets_heading_present check (heading <> ''),
  constraint lead_magnets_button_label_present check (button_label <> ''),
  -- An href, so the same rule as authors' social links: http(s) or nothing.
  -- Enforced here as well as in the server action because this value is
  -- rendered into a link a reader clicks.
  constraint lead_magnets_asset_url_http check (
    asset_url is null or asset_url ~* '^https?://'
  )
);

create index lead_magnets_site_idx on public.lead_magnets (site_id);

create trigger lead_magnets_touch_updated_at
  before update on public.lead_magnets
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- lead_magnet_targets
-- ---------------------------------------------------------------------------
-- One row per placement rule. A magnet with no rows appears nowhere, which is
-- the right default for a half-built offer.

create type lead_magnet_scope as enum ('site', 'category', 'tag', 'post');

create table public.lead_magnet_targets (
  id         uuid primary key default gen_random_uuid(),
  magnet_id  uuid not null references public.lead_magnets(id) on delete cascade,
  scope      lead_magnet_scope not null,

  /*
   * Two nullable foreign keys rather than one polymorphic `target_id uuid`.
   *
   * A single column pointing at either terms or posts cannot carry a foreign
   * key, so deleting a category would leave a rule silently targeting nothing —
   * and "the widget stopped appearing" is close to undiagnosable from the admin
   * screen. With real FKs the cascade removes the rule instead.
   */
  term_id    uuid references public.terms(id) on delete cascade,
  post_id    uuid references public.posts(id) on delete cascade,

  created_at timestamptz not null default now(),

  -- Exactly the column the scope names, and no other.
  constraint lead_magnet_targets_shape check (
    case scope
      when 'site'     then term_id is null and post_id is null
      when 'post'     then post_id is not null and term_id is null
      else                 term_id is not null and post_id is null
    end
  )
);

/*
 * Three partial unique indexes rather than one unique constraint.
 *
 * A plain `unique (magnet_id, scope, term_id, post_id)` does not deduplicate
 * the site-wide rule: nulls are distinct in a unique index, so a magnet could
 * hold ten identical ('site', null, null) rows and each would be joined
 * separately. These say what is actually meant.
 */
create unique index lead_magnet_targets_site_unique
  on public.lead_magnet_targets (magnet_id)
  where scope = 'site';

create unique index lead_magnet_targets_term_unique
  on public.lead_magnet_targets (magnet_id, term_id)
  where term_id is not null;

create unique index lead_magnet_targets_post_unique
  on public.lead_magnet_targets (magnet_id, post_id)
  where post_id is not null;

-- The resolver's read path: given a post's id and its term ids, which rules
-- match. Indexed from the target side because that is the filtered column.
create index lead_magnet_targets_term_idx on public.lead_magnet_targets (term_id);
create index lead_magnet_targets_post_idx on public.lead_magnet_targets (post_id);
create index lead_magnet_targets_magnet_idx on public.lead_magnet_targets (magnet_id);

-- ---------------------------------------------------------------------------
-- leads
-- ---------------------------------------------------------------------------

create table public.leads (
  id           uuid primary key default gen_random_uuid(),
  site_id      uuid not null references public.sites(id) on delete cascade,

  /*
   * `on delete set null`, and the slug denormalised beside it.
   *
   * Deleting a magnet must not delete the people who asked for it — that is
   * destroying the only thing of value the feature produced. The slug is kept
   * as text so an export still says what they signed up for after the row it
   * pointed at is gone.
   */
  magnet_id    uuid references public.lead_magnets(id) on delete set null,
  magnet_slug  text not null,

  email        text not null,
  name         text,

  -- Which post converted them, and what sent them there. Both are the whole
  -- point of capturing per-post rather than site-wide: without source_path you
  -- cannot tell which article earns its offer.
  source_path  text,
  referrer     text,
  utm          jsonb not null default '{}'::jsonb,

  /*
   * Bumped on a repeat submission instead of writing a second row — see
   * capture_lead below. Someone who requests the same file twice is one lead
   * who lost the first email, not two.
   */
  submissions  integer not null default 1,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint leads_email_present check (email <> ''),
  constraint leads_utm_is_object check (jsonb_typeof(utm) = 'object')
);

-- Case-insensitively unique per offer. Expression index rather than storing a
-- lowercased copy: the address is shown back to a human in the admin, and
-- Denis@ is how they typed it.
create unique index leads_email_per_magnet_unique
  on public.leads (site_id, magnet_slug, lower(email));

create index leads_site_created_idx on public.leads (site_id, created_at desc);
create index leads_magnet_idx on public.leads (magnet_id);

create trigger leads_touch_updated_at
  before update on public.leads
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- capture_lead
-- ---------------------------------------------------------------------------
-- The ONLY write path anonymous traffic has into this schema.
--
-- The blog deployment holds the anon key and nothing else — the service-role
-- key must never be set there (see the security model in the README), and this
-- feature is not a reason to change that. So rather than granting anon `insert`
-- on `leads`, which would also let anyone with the key write arbitrary rows for
-- any site, the grant is on one security-definer function that:
--
--   * refuses unless the magnet exists, belongs to that site and is active, so
--     a submission cannot invent an offer or reactivate a retired one;
--   * decides the site_id and magnet_slug itself from the looked-up row rather
--     than trusting either from the caller;
--   * only ever touches `leads`, and only this one shape of row.
--
-- Anon still cannot SELECT from leads — there is no grant and no policy — so
-- the function is write-only from the outside. The email-exists oracle that a
-- readable table would hand out is closed by returning the same result whether
-- the row was new or bumped.

create function public.capture_lead(
  p_site_slug    text,
  p_magnet_slug  text,
  p_email        text,
  p_name         text default null,
  p_source_path  text default null,
  p_referrer     text default null,
  p_utm          jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_magnet public.lead_magnets%rowtype;
begin
  select m.* into v_magnet
  from public.lead_magnets m
  join public.sites s on s.id = m.site_id
  where s.slug = p_site_slug
    and m.slug = p_magnet_slug
    and m.active;

  if not found then
    -- Named rather than generic: this fires during setup far more often than in
    -- production, and "no active lead magnet" is the answer to why the form
    -- silently did nothing.
    raise exception 'No active lead magnet % on site %', p_magnet_slug, p_site_slug
      using errcode = 'no_data_found';
  end if;

  if p_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Not an email address' using errcode = 'check_violation';
  end if;

  insert into public.leads (
    site_id, magnet_id, magnet_slug, email, name, source_path, referrer, utm
  )
  values (
    v_magnet.site_id,
    v_magnet.id,
    v_magnet.slug,
    trim(p_email),
    nullif(trim(coalesce(p_name, '')), ''),
    nullif(trim(coalesce(p_source_path, '')), ''),
    nullif(trim(coalesce(p_referrer, '')), ''),
    coalesce(p_utm, '{}'::jsonb)
  )
  on conflict (site_id, magnet_slug, lower(email)) do update
    set submissions = leads.submissions + 1,
        -- Re-requesting from a different article is worth knowing; the first
        -- source is not, once they have converted twice.
        source_path = coalesce(excluded.source_path, leads.source_path),
        -- Kept if it was ever supplied. A second submission with the name field
        -- left blank should not erase the name from the first.
        name        = coalesce(excluded.name, leads.name),
        utm         = case when leads.utm = '{}'::jsonb
                          then excluded.utm else leads.utm end;
end;
$$;

revoke all on function public.capture_lead(text, text, text, text, text, text, jsonb) from public;
grant execute on function public.capture_lead(text, text, text, text, text, text, jsonb)
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Privileges and RLS
-- ---------------------------------------------------------------------------
-- 0002 revokes everything from anon and authenticated across the schema and
-- re-grants explicitly, so a new table with a good policy and no grant returns
-- a permission error rather than an empty set.

alter table public.lead_magnets        enable row level security;
alter table public.lead_magnet_targets enable row level security;
alter table public.leads               enable row level security;

-- Anon reads the offer and its placement rules — the blog renders both at build
-- and revalidation time. It gets NO grant on `leads`: email addresses, same
-- reasoning as `profiles` in 0001.
grant select on public.lead_magnets, public.lead_magnet_targets to anon;

grant select, insert, update, delete
  on public.lead_magnets, public.lead_magnet_targets to authenticated;

-- Read and delete only. A lead is a record of something a visitor did, and an
-- admin screen that can edit it is an admin screen that can quietly rewrite the
-- evidence. Delete stays, because a GDPR erasure request has to be answerable.
grant select, delete on public.leads to authenticated;

-- Only ACTIVE magnets are public. An offer being drafted is not yet an offer,
-- and the anon key is readable by anyone who views source on the blog.
create policy lead_magnets_public_read on public.lead_magnets
  for select to anon, authenticated
  using (active);

create policy lead_magnets_editor_write on public.lead_magnets
  for all to authenticated
  using (public.has_site_role(site_id, 'editor'))
  with check (public.has_site_role(site_id, 'editor'));

/*
 * Targets are readable when their magnet is. The subquery cannot just be
 * `exists (select 1 from lead_magnets ...)` filtered by `active` alone: an
 * editor reading their own draft magnet's rules needs them too, so this mirrors
 * the two conditions above rather than restating one of them.
 */
create policy lead_magnet_targets_public_read on public.lead_magnet_targets
  for select to anon, authenticated
  using (
    exists (
      select 1 from public.lead_magnets m
      where m.id = magnet_id
        and (m.active or public.has_site_role(m.site_id, 'editor'))
    )
  );

create policy lead_magnet_targets_editor_write on public.lead_magnet_targets
  for all to authenticated
  using (
    exists (
      select 1 from public.lead_magnets m
      where m.id = magnet_id and public.has_site_role(m.site_id, 'editor')
    )
  )
  with check (
    exists (
      select 1 from public.lead_magnets m
      where m.id = magnet_id and public.has_site_role(m.site_id, 'editor')
    )
  );

-- `admin`, not `editor`. Someone trusted to write posts and configure offers is
-- not automatically someone who should be able to read or erase the mailing
-- list those offers produced.
create policy leads_admin_read on public.leads
  for select to authenticated
  using (public.has_site_role(site_id, 'admin'));

create policy leads_admin_delete on public.leads
  for delete to authenticated
  using (public.has_site_role(site_id, 'admin'));
