-- 0015_proof_notifications.sql — social-proof toasts ("James from San Diego,
-- CA got the guide · 7 min ago")
--
-- The SaaS equivalent is Provenly or ProveSource: a small card that slides in
-- at a corner of the page and cycles through recent activity. Three tables:
--
--   proof_campaigns         one rotating toast — its look, timing and image
--   proof_events            the messages it cycles through, in order
--   proof_campaign_targets  where it is allowed to appear
--
-- WHY THE EVENTS ARE A HAND-KEPT LIST. They are typed or pasted in the admin,
-- the way Provenly reads them from a Google Sheet. Nothing here invents
-- activity: the admin shows a reminder to use real activity, because in a
-- regulated business a toast saying someone did something they did not is a
-- deceptive claim, not a design choice.
--
-- WHY TARGETS COPY lead_magnet_targets, PLUS PATHS. Lead magnets only ever ran
-- on posts, so category / tag / post covered it. A toast runs on any route —
-- the home page, marketing pages, calculators — so it also takes a URL pattern,
-- and any rule can be an exclusion ("everywhere except /get-started").
--
-- Copy is plain text for the reason 0010 gives: it is rendered as text and
-- needs no sanitiser allowlist.

-- ---------------------------------------------------------------------------
-- proof_campaigns
-- ---------------------------------------------------------------------------

create type proof_template as enum ('pill', 'card');
create type proof_image_mode as enum ('none', 'preset', 'custom', 'map');
create type proof_position as enum ('bottom-left', 'bottom-right', 'top-left', 'top-right');
create type proof_frequency as enum ('every_page', 'once_per_session');

create table public.proof_campaigns (
  id              uuid primary key default gen_random_uuid(),
  site_id         uuid not null references public.sites(id) on delete cascade,

  -- Internal label for the admin list. Never rendered to a reader.
  name            text not null,

  /*
   * `pill` is a fully rounded capsule with a round image (Provenly);
   * `card` is a rectangle with rounded corners and a square image
   * (ProveSource).
   */
  template        proof_template not null default 'pill',

  /*
   * What sits on the left of the toast.
   *
   *   none    text only
   *   preset  one of the built-in icons named by `preset_icon`
   *   custom  `image_id`, an image from the media library
   *   map     a map of each event's own city, generated by the admin on save
   *           (proof_events.map_path) — falls back to the preset icon for any
   *           event whose place could not be found
   *
   * An event can override the picture with its own `image_id` in any mode
   * except `none`.
   */
  image_mode      proof_image_mode not null default 'preset',
  preset_icon     text not null default 'fire',
  /*
   * The only foreign key from this table to `media`, for the reason 0011
   * gives: the public query embeds it as `image:media(…)`, which PostgREST can
   * only resolve while one key could satisfy it.
   */
  image_id        uuid references public.media(id) on delete set null,

  position        proof_position not null default 'bottom-left',
  show_on_mobile  boolean not null default true,

  -- Seconds. Before the first toast, how long each stays, and the pause between.
  initial_delay_s integer not null default 5,
  display_s       integer not null default 6,
  gap_s           integer not null default 8,
  -- Toasts per page view. Past this the campaign goes quiet until the next page.
  max_per_view    integer not null default 5,
  -- Start again from the first event after the last, within max_per_view.
  repeat_events   boolean not null default true,
  frequency       proof_frequency not null default 'every_page',
  show_time_ago   boolean not null default true,
  -- Colour of the name link and the check mark. A hex value, or null for the
  -- default blue.
  accent          text,

  -- Off rather than deleted, so a seasonal campaign keeps its list.
  active          boolean not null default true,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint proof_campaigns_name_present check (name <> ''),
  constraint proof_campaigns_preset_icon_known check (
    preset_icon in ('fire', 'check', 'cart', 'star', 'bell', 'gift', 'download', 'user')
  ),
  constraint proof_campaigns_accent_hex check (
    accent is null or accent ~* '^#[0-9a-f]{6}$'
  ),
  constraint proof_campaigns_timing_sane check (
    initial_delay_s between 0 and 600
    and display_s between 2 and 60
    and gap_s between 0 and 600
    and max_per_view between 1 and 50
  )
);

create index proof_campaigns_site_idx on public.proof_campaigns (site_id);

create trigger proof_campaigns_touch_updated_at
  before update on public.proof_campaigns
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- proof_events
-- ---------------------------------------------------------------------------

create table public.proof_events (
  id              uuid primary key default gen_random_uuid(),
  campaign_id     uuid not null references public.proof_campaigns(id) on delete cascade,
  -- Denormalised from the campaign so RLS can be checked without a join.
  site_id         uuid not null references public.sites(id) on delete cascade,
  -- Display order. The admin rewrites the whole list on save, 0..n-1.
  sort            integer not null default 0,

  -- "James from San Diego, CA". A blank name renders as "Someone".
  name            text,
  city            text,
  region          text,
  country         text,
  -- "recently got the Equipment Financing Guide"
  action          text not null,

  /*
   * A RANGE, not a timestamp. The list is hand-kept, so a stored time would
   * read "3 weeks ago" a month after it was typed. The reader's browser picks a
   * value inside the range each time the toast is shown.
   */
  minutes_ago_min integer not null default 2,
  minutes_ago_max integer not null default 60,

  -- Optional. With one, the whole toast is a link.
  link_url        text,

  -- Overrides the campaign's picture for this event. The only FK to media.
  image_id        uuid references public.media(id) on delete set null,

  /*
   * The map, for image_mode = 'map'. Filled in by the admin on save: the place
   * is geocoded with OpenStreetMap's Nominatim, a small map is rendered from
   * OSM tiles and stored in the `media` bucket under proof-maps/. Readers'
   * browsers load that stored image and never call OpenStreetMap themselves.
   *
   * `map_place` is the place string the map was drawn for, so a save only
   * redraws maps whose city actually changed.
   */
  lat             double precision,
  lng             double precision,
  map_path        text,
  map_place       text,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint proof_events_action_present check (action <> ''),
  constraint proof_events_minutes_sane check (
    minutes_ago_min >= 0 and minutes_ago_max >= minutes_ago_min
  ),
  -- Rendered into a link a reader clicks: http(s) or a site-relative path.
  constraint proof_events_link_safe check (
    link_url is null or link_url ~* '^(https?://|/[^/])' or link_url = '/'
  )
);

create index proof_events_campaign_idx on public.proof_events (campaign_id, sort);
create index proof_events_site_idx on public.proof_events (site_id);

create trigger proof_events_touch_updated_at
  before update on public.proof_events
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- proof_campaign_targets
-- ---------------------------------------------------------------------------
-- One row per rule. A campaign with no include rule appears nowhere, which is
-- the right default for a half-built one.

create type proof_target_scope as enum ('site', 'path', 'category', 'tag', 'post');

create table public.proof_campaign_targets (
  id          uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.proof_campaigns(id) on delete cascade,
  scope       proof_target_scope not null,
  -- True: a page this rule matches never shows the campaign, whatever else
  -- matches it.
  exclude     boolean not null default false,

  -- Real foreign keys, for the reason 0010 gives for lead_magnet_targets.
  term_id     uuid references public.terms(id) on delete cascade,
  post_id     uuid references public.posts(id) on delete cascade,
  -- For scope = 'path': an exact path, `/blog/` + `*` (one segment below) or
  -- `/blog/` + `**` (anything below). Line comments, because Postgres nests
  -- block comments and the pattern syntax itself opens one. Matching is
  -- pathMatches in packages/core/src/proof.ts.
  pattern     text,

  created_at  timestamptz not null default now(),

  constraint proof_campaign_targets_shape check (
    case scope
      when 'site'     then term_id is null and post_id is null and pattern is null
      when 'post'     then post_id is not null and term_id is null and pattern is null
      when 'path'     then pattern is not null and term_id is null and post_id is null
      else                 term_id is not null and post_id is null and pattern is null
    end
  ),
  constraint proof_campaign_targets_pattern_rooted check (
    pattern is null or pattern ~ '^/'
  )
);

create index proof_campaign_targets_campaign_idx on public.proof_campaign_targets (campaign_id);
create index proof_campaign_targets_term_idx on public.proof_campaign_targets (term_id);
create index proof_campaign_targets_post_idx on public.proof_campaign_targets (post_id);

-- ---------------------------------------------------------------------------
-- Privileges and RLS
-- ---------------------------------------------------------------------------
-- Same shape as 0010: anon reads active campaigns and what hangs off them,
-- editors write. There is nothing private in any of these tables — they exist
-- to be shown to every visitor — but a draft campaign is not yet public.
--
-- The child tables give anon a read policy of its own that never calls
-- has_site_role. 0002 grants that function to `authenticated` only, so a
-- policy shared with anon works solely because a Supabase project's default
-- privileges also grant it to anon directly — true today, but not something
-- this table's public read should rest on.

alter table public.proof_campaigns        enable row level security;
alter table public.proof_events           enable row level security;
alter table public.proof_campaign_targets enable row level security;

grant select on public.proof_campaigns, public.proof_events, public.proof_campaign_targets
  to anon;

grant select, insert, update, delete
  on public.proof_campaigns, public.proof_events, public.proof_campaign_targets
  to authenticated;

create policy proof_campaigns_public_read on public.proof_campaigns
  for select to anon, authenticated
  using (active);

create policy proof_campaigns_editor_write on public.proof_campaigns
  for all to authenticated
  using (public.has_site_role(site_id, 'editor'))
  with check (public.has_site_role(site_id, 'editor'));

create policy proof_events_public_read on public.proof_events
  for select to anon
  using (
    exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id and c.active
    )
  );

create policy proof_events_member_read on public.proof_events
  for select to authenticated
  using (
    exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id
        and (c.active or public.has_site_role(c.site_id, 'editor'))
    )
  );

create policy proof_events_editor_write on public.proof_events
  for all to authenticated
  using (public.has_site_role(site_id, 'editor'))
  with check (
    public.has_site_role(site_id, 'editor')
    and exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id and c.site_id = proof_events.site_id
    )
  );

create policy proof_campaign_targets_public_read on public.proof_campaign_targets
  for select to anon
  using (
    exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id and c.active
    )
  );

create policy proof_campaign_targets_member_read on public.proof_campaign_targets
  for select to authenticated
  using (
    exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id
        and (c.active or public.has_site_role(c.site_id, 'editor'))
    )
  );

create policy proof_campaign_targets_editor_write on public.proof_campaign_targets
  for all to authenticated
  using (
    exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id and public.has_site_role(c.site_id, 'editor')
    )
  )
  with check (
    exists (
      select 1 from public.proof_campaigns c
      where c.id = campaign_id and public.has_site_role(c.site_id, 'editor')
    )
  );
